# Generated by Django 4.0.3 on 2022-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("id_number", models.CharField(default="", max_length=255)),
                ("account", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(default="", max_length=255)),
                ("bankaccount", models.TextField(default="", max_length=255)),
                ("budget", models.FloatField(default=10000)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
