# Generated by Django 4.0.3 on 2022-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="picture",
            field=models.TextField(default=""),
        ),
    ]
