# Generated by Django 4.0.3 on 2022-04-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='budget',
            field=models.FloatField(default=10000),
        ),
    ]
