# Generated by Django 4.0.3 on 2022-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0002_remove_myuser_credits_remove_myuser_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="account",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
