# Generated by Django 4.0.3 on 2022-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAM', '0002_alter_myuser_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bankaccount',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
