# Generated by Django 4.0.3 on 2022-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0003_alter_myuser_account_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="id_number",
            field=models.CharField(max_length=10),
        ),
    ]
