# Generated by Django 4.0.3 on 2022-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0004_alter_myuser_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="account",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="id_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
