# Generated by Django 4.0.3 on 2022-04-23 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0005_alter_myuser_account_alter_myuser_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="bankaccount",
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
