# Generated by Django 4.0.3 on 2022-04-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(default="我是一個投資組合")),
                ("description", models.TextField(default="世界你好")),
                ("follow_price", models.FloatField(blank=True, default=1000)),
                ("budget", models.FloatField(blank=True, default=10000)),
                ("is_public", models.BooleanField(default=False)),
                ("is_alive", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "portfolio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.TextField()),
                ("name", models.TextField()),
                ("group", models.TextField()),
            ],
            options={
                "db_table": "stock",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField()),
                ("time", models.DateTimeField()),
                ("price", models.FloatField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        db_column="portfolio", on_delete=django.db.models.deletion.CASCADE, to="engine.portfolio"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="stock", on_delete=django.db.models.deletion.CASCADE, to="engine.stock"
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stockprice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField()),
                ("price", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        db_column="stock", on_delete=django.db.models.deletion.CASCADE, to="engine.stock"
                    ),
                ),
            ],
            options={
                "db_table": "stockprice",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starttime", models.DateTimeField()),
                ("budget", models.FloatField()),
                ("is_alive", models.BooleanField(default=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        db_column="portfolio", on_delete=django.db.models.deletion.CASCADE, to="engine.portfolio"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "follow",
                "managed": True,
            },
        ),
    ]
