# Generated by Django 4.0.3 on 2022-04-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="price",
            new_name="cash",
        ),
    ]
