# Generated by Django 4.0.3 on 2022-04-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_alter_stockprice_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="stock",
            field=models.ForeignKey(
                db_column="stock", on_delete=django.db.models.deletion.CASCADE, related_name="price", to="engine.stock"
            ),
        ),
    ]
