# Generated by Django 4.0.3 on 2022-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_rename_price_portfolio_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="code",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
