# Generated by Django 4.0.3 on 2022-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_portfolio_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
