# Generated by Django 4.0.3 on 2022-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_alter_follow_id_alter_portfolio_id_alter_stock_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget",
            field=models.FloatField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="budget",
            field=models.FloatField(blank=True, default=10000),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="cash",
            field=models.FloatField(blank=True, default=10000),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default="世界你好"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.TextField(default="我是一個投資組合"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bankaccount",
            field=models.TextField(default="123456789"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.TextField(default="iHaveNoEmail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.TextField(blank=True, default="A123456789"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(default="我是已閱讀並同意以上條款的帳號"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(default=""),
        ),
    ]
