# Generated by Django 4.0.3 on 2022-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_user_budget_alter_portfolio_budget_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="cash",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="cash",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="follow_price",
            field=models.FloatField(blank=True, default=1000),
        ),
    ]
