# Generated by Django 4.0.3 on 2022-04-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_remove_follow_cash_remove_portfolio_cash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="endtime",
        ),
    ]
