# Generated by Django 4.0.3 on 2022-04-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_remove_follow_endtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="stop_limit",
        ),
    ]
